//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.dirEntrega = new HashSet<dirEntrega>();
            this.OrdenCliente = new HashSet<OrdenCliente>();
        }
    
        public int id_cliente { get; set; }
        [Display(Name = "Nombre Completo")]
        [Required(ErrorMessage = "Requiere ser mayor o menor")]
        public string nombre { get; set; }

        public string email { get; set; }
        [Display(Name ="Calle y Numero")]
        public string calle { get; set; }
        [Display(Name = "Colonia")]
        public string colonia { get; set; }
        [Display(Name = "Estado")]
        public string estado { get; set; }
        [Display(Name = "N° de tarjeta de credito")]
        [Required(ErrorMessage = "Requerido")]
        [Range(100000000000,9999999999999999,ErrorMessage ="Debe ser entre 12 y 16 digitos")]
        public Nullable<int> num_tarjeta_credito { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dirEntrega> dirEntrega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCliente> OrdenCliente { get; set; }
    }
}
